<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2012-02-18 00:06

$extensionPath = t3lib_extMgm::extPath('maintenance');
$extensionClassesPath = $extensionPath . 'classes/';
return array(
	'tx_maintenance_maintenance' => $extensionClassesPath . 'Maintenance.php',
	'tx_maintenance_configuration_abstractconfiguration' => $extensionClassesPath . 'Configuration/AbstractConfiguration.php',
	'tx_maintenance_configuration_devipmask' => $extensionClassesPath . 'Configuration/DevIPMask.php',
	'tx_maintenance_configuration_pageunavailablehandling' => $extensionClassesPath . 'Configuration/PageUnavailableHandling.php',
	'tx_maintenance_configuration_pageunavailablehandlingstatheader' => $extensionClassesPath . 'Configuration/PageUnavailableHandlingStatheader.php',
	'tx_maintenance_extdirect_toolbaritem' => $extensionClassesPath . 'ExtDirect/ToolbarItem.php',
	'tx_maintenance_reports_configuration' => $extensionClassesPath . 'Reports/Configuration.php',
);
?>